### PR TITLE
Offchain Spec (WIP)

### PR DESCRIPTION
**Pull request by lamafab**
Some adjustments based on your feedback. I'll follow up with the rest tomorrow. Just in case you wanted to take a look.

### CODE REVIEW

**Comment by tomaka** [comment]
For what it's worth, the HTTP methods have more precise documentation in this file: https://github.com/paritytech/substrate/blob/3f6cbc851883a7e7638e81ea43cf2bfc5e2a3736/core/primitives/src/offchain.rs

**Comment by lamafab** [comment]
@tomaka Thanks, I already found that file, but a lot of the descriptions are Substrate specific and it's important to keep the spec Rust-independent. Certain areas (as marked in the file) must be expanded on.

**Comment by tomaka** [comment]
To me what's missing from this PR, and what the file I link contains, is in which situations it is legal to call these functions, and in which situation they might return an error.

**Comment by lamafab** [comment]
> To me what's missing from this PR, and what the file I link contains, is in which situations it is legal to call these functions, and in which situation they might return an error.

Okay, thanks for the feedback. I will adjust that.

**Pull request merged**
