### PR TITLE
Additional renames in README.md

### PR DESCRIPTION
**Pull request by lamafab**
This PR has more renames to "Polkadot Host", also renamed the directory containing the spec. Additionally, the Testing section of the README.md has been moved in its own `test/README.md`, leaving the main README.md cleaner.

### CODE REVIEW

**Review by FlorianFranzen — APPROVED** [review]
You forgot the [rust-tester `cli.yaml`](https://github.com/w3f/polkadot-spec/blob/master/test/testers/rust-tester/src/cli.yaml). :wink:

**Comment by drskalman** [comment]
Shouldn't all polkadot_re_spec in https://github.com/w3f/polkadot-spec/tree/repo-rename-to-host/polkadot-host-spec folder become polkadot_host_spec (including the bibtex files)?

**Comment by lamafab** [comment]
@FlorianFranzen @drskalman Additional renames in C++/Go tester, also renamed the spec files themselves.

**Review by FlorianFranzen — APPROVED** [review]
Good catch. Looks good to me. LGTM! :+1:

**Comment by FlorianFranzen** [comment]
Looks like we forgot to update the links in the readme,  see #155.

**Pull request merged**
