### PR TITLE
Update return type of `validate_transaction` + minor changes

### PR DESCRIPTION
**Pull request by lamafab**
This was requested by Kamil (Kagome).

This PR contains:
- Rename `BabeApi_epoch` to `BabeApi_configuration`, adjust return type [UPDATED].
- Remove the block number from the parameters passed to `validate_transaction`.
- Complete the spec of the `validate_transaction` return types.

**Printscreens**:
- Rename `BabeApi_epoch` to `BabeApi_configuration`, adjust return type [UPDATED].
image

- Remove the block number from the parameters passed to `validate_transaction`.
image

- Complete the spec of the `validate_transaction` return types.
image
image

### CODE REVIEW

**Comment by kamilsa** [comment]
5.2.1 Still mentions `BabeApi_epoch`, should be removed
Also it is listed in Runtime entries

**Comment by lamafab** [comment]
@kamilsa

> 5.2.1 Still mentions `BabeApi_epoch`, should be removed

Where exactly?

> Also it is listed in Runtime entries

Do you mean this list? It has been adjust (please clarify)
image

I

**Comment by kamilsa** [comment]
https://github.com/w3f/polkadot-spec/blob/718747e8f8da4d4fe936a1d6619d93c140c00d89/runtime-environment-spec/polkadot_re_spec.tm#L1103

https://github.com/w3f/polkadot-spec/blob/718747e8f8da4d4fe936a1d6619d93c140c00d89/runtime-environment-spec/polkadot_re_spec.tm#L2996

**Comment by lamafab** [comment]
@kamilsa Thanks. Updated!

**Comment by lamafab** [comment]
@kamilsa Thanks. Updated!

**Comment by lamafab** [comment]
@kamilsa Thanks. Updated!

**Comment by drskalman** [comment]
LGTM.

**Pull request merged**
