### PR TITLE
Update Kagome's Host API testsuite integration

### PR DESCRIPTION
**Pull request by FlorianFranzen**
Tasks left to do after the initial update triggered by #253:
 - [x] Update `kagome-adapter` to the latest Kagome API
 - [x] Split off old `host-api-legacy` test adapter to `kagome-adpater-legacy`
 - [x] Load and use `wasm-adapter` runtime instead of calling API directly 
 - [x] Update `kagome-adapter` to implement `host-api` fixture
 - [x] Update kagome source to master
 - [x] Remove false positives for fixtures without an expected output

### CODE REVIEW

**Comment by FlorianFranzen** [comment]
### Status host-api fixture

After removing all the false positives, this is the current result:
```
Test Summary: | Pass  Fail  Broken  Total
Host API      |  130    10     188    328
```
The broken test will be fixed over time by Soramitsu, so in the scope of this pull-request we will only need to fix the 10 failures. They all happen during the storage root test and a typical failure looks like this:
```
expected i64, seeing i32 from
0x834b90
expected i64, seeing i32 from
0x834bc0
expected i64, seeing i32 from
0x834bf8
kagome-adapter: /build/source/src/wasm/literal.cpp:299: wasm::Literal wasm::Literal::wrapToI32() const: Assertion `type == Type::i64' failed.
┌ Error: Adapter failed: ErrorException("failed process: Process(`kagome-adapter host-api --function ext_storage_root_version_1 --input static,Inverse,even-keeled,Future-proofed`, ProcessSignaled(6)) [0]")
└ @ Main.SpecificationTestsuite.AdapterFixture ~/Projects/Web3/polkadot-spec-tests/test/helpers/AdapterFixture.jl:146
Host API: Test Failed at /home/florian/Projects/Web3/polkadot-spec-tests/test/helpers/AdapterFixture.jl:148
  Expression: false
Stacktrace:
 [1] run(::Main.SpecificationTestsuite.AdapterFixture.Builder, ::String) at /home/florian/Projects/Web3/polkadot-spec-tests/test/helpers/AdapterFixture.jl:148
 [2] macro expansion at /home/florian/Projects/Web3/polkadot-spec-tests/test/helpers/AdapterFixture.jl:166 [inlined]
 [3] macro expansion at /build/source/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
 [4] #execute#1(::Bool, ::Function, ::Main.SpecificationTestsuite.AdapterFixture.Builder) at /home/florian/Projects/Web3/polkadot-spec-tests/test/helpers/AdapterFixture.jl:159
```

**Comment by FlorianFranzen** [comment]
The remaining failures should be fixed by soramitsu/kagome#505.

**Comment by FlorianFranzen** [comment]
Failure was not fixed by soramitsu/kagome#505 and required additional patching as submitted with soramitsu/kagome#506.

**Comment by FlorianFranzen** [comment]
I overlooked some missing fixes in the testsuite, so my PR was replaced by soramitsu/kagome#508.

**Review by lamafab — APPROVED** [review]
Went through the commits together with Florian via Hangouts. OK from me.

**Pull request merged**
