### PR TITLE
Add support for kaitai struct definition

### PR DESCRIPTION
**Pull request by FlorianFranzen**
This PR adds the new `asciidoctor-kaitai` extension that allow us to embed kaitai definition in the spec.

- [x] Fix nix CI failures
- [x] Add proper asciidoctor converter for kaitai export (right now exports are build on the side)
- [x] Parse current metadata with parser resulting from export

### CODE REVIEW

**Comment by lamafab** [comment]
What's that `.ksy` file?

**Comment by FlorianFranzen** [comment]
Those are some basic kaitai definitions to parse some basic scale types. See the [kaitai struct language](https://doc.kaitai.io/user_guide.html#_kaitai_struct_language) for details.

**Comment by FlorianFranzen** [comment]
- [x] Split structures
- [x] Check for discrepencies

**Comment by FlorianFranzen** [comment]
The kaitiai integration is ready, the remaining discrepancies will be resolved in the review of #517.

**Pull request merged**
