### PR TITLE
Merge the Networking, A&V and Messaging chapter into Host Specification

### PR DESCRIPTION
**Pull request by FlorianFranzen**
### Description

This PR add the previously separate networking, availability and validity and messaging chapter to the host-spec, converted into the TeXmacs format.

Furthermore this rebuilds the toc, index, glossary and bibliography for every build now.

### Known issues (to be resolved in a seperate PR)
 - Algorithms need some touch ups after conversion
 - TeXmacs on CI fails to convert svg graphics
 - Some broken references

### CODE REVIEW

**Comment by lamafab** [comment]
@lamafab review this. @drskalman already looked at this: looks good.

**Review by lamafab — APPROVED** [review]
Discussed with Florian directly. LGTM.

**Comment by lamafab** [comment]
@FlorianFranzen will merge this ASAP (Texmacs).

**Comment by drskalman** [comment]
@FlorianFranzen is at the end of rewriting the algorithm and will submit it for review by the rest of the team before the end of the week.

**Review by lamafab — APPROVED** [review]

**Comment by lamafab** [comment]
LGTM. Make sure to update the buffer (table of contents, etc.)

**Comment by FlorianFranzen** [comment]
@lamafab Ok, just updated TOC and friends. 

Also took a quick look at the broken internal references and saw that most of them are typos so I fixed them as well. 

I will wait for the CI to finish before I merge into master.

**Pull request merged**
